<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function dsawm_custom_block_info() {

    $blocks['landing_header'] = array(
        // info: The name of the block.
        'info' => t('Resource Landing Header')

    );
    $blocks['footer_old'] = array(
        // info: The name of the block.
        'info' => t('Footer block')

    );
    return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function dsawm_custom_block_configure($delta = '') {
    $form = array();
    if ($delta == 'landing_header') {
        $default = '<div class="resource-header"><div class="header-left img-shadow"><img class="header-image" src="/sites/all/themes/d7theme/images/header-landing.png" /></div><div class="header-right"><h2>Resources</h2><p>
        The Down Syndrome Association of West Michigan (DSAWM) assembled a list of helpful resources and information relevant to individuals with Down syndrome, their families and friends, and interested community members. Please select from the categories below to get started. If you have any questions or need further assistance, please contact the DSAWM Administrative Assistant, Audrey Day, at audrey@dsawm.org.

        </p></div></div>';

        $form['landing_header_content'] = array(
            '#type' => 'text_format',
            '#title' => t('Block contents'),
            '#size' => 60,
            '#description' => t('This text will appear in the landing header.'),
            '#default_value' => variable_get('landing_header_content', $default),
        );

    }

    if ($delta == 'footer_old'){
        $default = '
        <div id="affiliates">
            <p>The Down Syndrome Association of West Michigan is an affiliate of:</p>

            <a href="http://www.ndss.org" target="_blank">
                <img src="/sites/all/themes/d7theme/images/NDSS.png" width="77" height="40"  alt="">
            </a>
            <a href="http://www.ndsccenter.org">
                <img border="0" alt="National Down Syndrome Congress" width="115" height="35" src="/sites/all/themes/d7theme/images/ndsc.jpg">
            </a
            <a target="_blank" href="http://www.dsaia.org">
                <img border="0" alt="Down Syndrome Affiliates in Action" width="239" height="35" src="/sites/all/themes/d7theme/images/DSAIA.jpg">
            </a>
        </div>

        <div id="contact-info">
            <p>Copyright © 2012 Down Syndrome Association of West Michigan</p>
            <p>233 E Fulton St, Ste 108 | Grand Rapids, MI 49503</p>
            <p><strong>Phone:  616-956-3488</br>Toll Free 866-665-7451</strong></p>
        </div>
        ';
        $form['footer_old_content'] = array(
            '#type' => 'text_format',
            '#title' => t('Block contents'),
            '#size' => 60,
            '#description' => t('This text will appear in the footer.'),
            '#default_value' => variable_get('footer_old_content', $default),
        );

    }
    return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function dsawm_custom_block_save($delta = '', $edit = array()) {

    if ($delta == 'landing_header') {
        variable_set('landing_header_content', $edit['landing_header_content']['value']);
    }

    if ($delta == 'footer_old') {
        variable_set('footer_old', $edit['footer_old_content']['value']);
    }
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function dsawm_custom_block_view($delta = '') {
    switch ($delta) {
        case 'landing_header':
            $default = '<div class="resource-header"><div class="header-left img-shadow"><img class="header-image" src="/sites/all/themes/d7theme/images/header-landing.png" /></div><div class="header-right"><h2>Resources</h2><p>The Down Syndrome Association of West Michigan (DSAWM) has assembled a list of helpful resources that are relevant to individuals with Down syndrome, their families and friends, and interested community members. Select the category in which you are interested to get started. If you have any questions or need further assistance, please contact the DSAWM Administrative Assistant, Audrey Day, at audrey@dsawm.org.</p></div></div>';
            $block['subject'] = t('');
            $content =  variable_get('landing_header_content', $default);

            $block['content'] = $content;
            break;

        case 'footer_old':
            $default = '
            <div id="affiliates">
                <p>The Down Syndrome Association of West Michigan is an affiliate of:</p>

                <a href="http://www.ndss.org" target="_blank">
                    <img src="/sites/all/themes/d7theme/images/NDSS.png" width="77" height="40"  alt="">
                </a>
                <a href="http://www.ndsccenter.org">
                    <img border="0" alt="National Down Syndrome Congress" width="115" height="35" src="/sites/all/themes/d7theme/images/ndsc.jpg">
                </a
                <a target="_blank" href="http://www.dsaia.org">
                    <img border="0" alt="Down Syndrome Affiliates in Action" width="239" height="35" src="/sites/all/themes/d7theme/images/DSAIA.jpg">
                </a>
            </div>

            <div id="contact-info">
                <p>Copyright © 2013 Down Syndrome Association of West Michigan</p>
                <p>233 E Fulton St, Ste 108 | Grand Rapids, MI 49503</p>
                <p><strong>Phone:  616-956-3488</br>Toll Free 866-665-7451</strong></p>
            </div>
            ';
            $block['subject'] = t('');
            $content =  variable_get('footer_old_content', $default);

            $block['content'] = $content;
            break;
    }
    return $block;
}
